### NOTE: schedule-strigger can only run on `default` branch.
name: Update versions of multiple .spec files

on:  # Trigger manually or on a schedule (e.g., weekly)
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 18 * * 5' # 18:00 on Friday, https://en.wikipedia.org/wiki/Cron
  push:
    branches: [ dev]  # Trigger on push to `dev` branch

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: dev    # Selected branch, default is `main`

    ### Fetch updated versions and save to file `_changed_specs.txt`
      - name: Update .spec files
        run: |
          bash 0update_spec_version.sh

    ### Commit and Push to the current repository (selected branch)
      - name: Commit and Push Changes back to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update versions in multiple .spec files"


    ### Push updates to multiple branches (create if not exists): each .spec file for a branch, e.g., branch `up_foo` for file `foo.spec`
      - name: Push updates to multiple branches
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          ### Read changed specs and push updates directly
          while IFS= read -r spec; do
            [ -z "$spec" ] && continue
            pkg=$(basename "$spec" .spec)
            branch="up_${pkg}"

            echo "==> Updating branch: $branch based on $spec"

            ## Create a temporary isolated, history-free (orphan) environment and add only the single .spec file
            ## 4b825dc642cb6eb9a030e54d74e2e1aa7429177f is the magic SHA for an empty git tree (a repository with absolutely zero files and no history).
            ## with `--detach`, you are telling Git: "Drop me into a temporary state where the working directory is completely blank and not tied to any branch."
            git checkout --detach 4b825dc642cb6eb9a030e54d74e2e1aa7429177f

            ## Bring the latest .spec file from the `dev` branch into this branch
            git checkout dev -- "$spec"
            git add "$spec"

            ## Commit and force-push directly to the target branch (create if not exists)
            if ! git diff --cached --quiet; then
              git commit -m "Auto update ${pkg}.spec from dev"
              git push origin HEAD:"refs/heads/$branch" --force
            else
              echo "No changes for $spec"
            fi
          done < _changed_specs.txt

          ### Ensure we leave the runner working directory back on the dev branch
          git checkout dev --force